/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminRecipesRouteImport } from './routes/_authenticated/admin/recipes'
import { Route as AuthenticatedPatientIndexRouteImport } from './routes/_authenticated/patient/index'
import { Route as AuthenticatedPatientLibraryRouteImport } from './routes/_authenticated/patient/library'
import { Route as AuthenticatedAdminPatientsIndexRouteImport } from './routes/_authenticated/admin/patients.index'
import { Route as AuthenticatedAdminPatientsIdRouteImport } from './routes/_authenticated/admin/patients.$id'
import { Route as AuthenticatedAdminPatientsNewRouteImport } from './routes/_authenticated/admin/patients.new'
import { Route as AuthenticatedPatientDayDayRouteImport } from './routes/_authenticated/patient/day.$day'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRecipesRoute =
  AuthenticatedAdminRecipesRouteImport.update({
    id: '/admin/recipes',
    path: '/admin/recipes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientIndexRoute =
  AuthenticatedPatientIndexRouteImport.update({
    id: '/patient/',
    path: '/patient/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientLibraryRoute =
  AuthenticatedPatientLibraryRouteImport.update({
    id: '/patient/library',
    path: '/patient/library',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPatientsIndexRoute =
  AuthenticatedAdminPatientsIndexRouteImport.update({
    id: '/admin/patients/',
    path: '/admin/patients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPatientsIdRoute =
  AuthenticatedAdminPatientsIdRouteImport.update({
    id: '/admin/patients/$id',
    path: '/admin/patients/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPatientsNewRoute =
  AuthenticatedAdminPatientsNewRouteImport.update({
    id: '/admin/patients/new',
    path: '/admin/patients/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientDayDayRoute =
  AuthenticatedPatientDayDayRouteImport.update({
    id: '/patient/day/$day',
    path: '/patient/day/$day',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/recipes': typeof AuthenticatedAdminRecipesRoute
  '/patient/library': typeof AuthenticatedPatientLibraryRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/patient/': typeof AuthenticatedPatientIndexRoute
  '/admin/patients/$id': typeof AuthenticatedAdminPatientsIdRoute
  '/admin/patients/new': typeof AuthenticatedAdminPatientsNewRoute
  '/patient/day/$day': typeof AuthenticatedPatientDayDayRoute
  '/admin/patients/': typeof AuthenticatedAdminPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/recipes': typeof AuthenticatedAdminRecipesRoute
  '/patient/library': typeof AuthenticatedPatientLibraryRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/patient': typeof AuthenticatedPatientIndexRoute
  '/admin/patients/$id': typeof AuthenticatedAdminPatientsIdRoute
  '/admin/patients/new': typeof AuthenticatedAdminPatientsNewRoute
  '/patient/day/$day': typeof AuthenticatedPatientDayDayRoute
  '/admin/patients': typeof AuthenticatedAdminPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/recipes': typeof AuthenticatedAdminRecipesRoute
  '/_authenticated/patient/library': typeof AuthenticatedPatientLibraryRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/patient/': typeof AuthenticatedPatientIndexRoute
  '/_authenticated/admin/patients/$id': typeof AuthenticatedAdminPatientsIdRoute
  '/_authenticated/admin/patients/new': typeof AuthenticatedAdminPatientsNewRoute
  '/_authenticated/patient/day/$day': typeof AuthenticatedPatientDayDayRoute
  '/_authenticated/admin/patients/': typeof AuthenticatedAdminPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/setup'
    | '/account'
    | '/change-password'
    | '/dashboard'
    | '/admin/recipes'
    | '/patient/library'
    | '/admin/'
    | '/patient/'
    | '/admin/patients/$id'
    | '/admin/patients/new'
    | '/patient/day/$day'
    | '/admin/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/setup'
    | '/account'
    | '/change-password'
    | '/dashboard'
    | '/admin/recipes'
    | '/patient/library'
    | '/admin'
    | '/patient'
    | '/admin/patients/$id'
    | '/admin/patients/new'
    | '/patient/day/$day'
    | '/admin/patients'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/setup'
    | '/_authenticated/account'
    | '/_authenticated/change-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/recipes'
    | '/_authenticated/patient/library'
    | '/_authenticated/admin/'
    | '/_authenticated/patient/'
    | '/_authenticated/admin/patients/$id'
    | '/_authenticated/admin/patients/new'
    | '/_authenticated/patient/day/$day'
    | '/_authenticated/admin/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/recipes': {
      id: '/_authenticated/admin/recipes'
      path: '/admin/recipes'
      fullPath: '/admin/recipes'
      preLoaderRoute: typeof AuthenticatedAdminRecipesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient/': {
      id: '/_authenticated/patient/'
      path: '/patient'
      fullPath: '/patient/'
      preLoaderRoute: typeof AuthenticatedPatientIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient/library': {
      id: '/_authenticated/patient/library'
      path: '/patient/library'
      fullPath: '/patient/library'
      preLoaderRoute: typeof AuthenticatedPatientLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/patients/': {
      id: '/_authenticated/admin/patients/'
      path: '/admin/patients'
      fullPath: '/admin/patients/'
      preLoaderRoute: typeof AuthenticatedAdminPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/patients/$id': {
      id: '/_authenticated/admin/patients/$id'
      path: '/admin/patients/$id'
      fullPath: '/admin/patients/$id'
      preLoaderRoute: typeof AuthenticatedAdminPatientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/patients/new': {
      id: '/_authenticated/admin/patients/new'
      path: '/admin/patients/new'
      fullPath: '/admin/patients/new'
      preLoaderRoute: typeof AuthenticatedAdminPatientsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient/day/$day': {
      id: '/_authenticated/patient/day/$day'
      path: '/patient/day/$day'
      fullPath: '/patient/day/$day'
      preLoaderRoute: typeof AuthenticatedPatientDayDayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminRecipesRoute: typeof AuthenticatedAdminRecipesRoute
  AuthenticatedPatientLibraryRoute: typeof AuthenticatedPatientLibraryRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedPatientIndexRoute: typeof AuthenticatedPatientIndexRoute
  AuthenticatedAdminPatientsIdRoute: typeof AuthenticatedAdminPatientsIdRoute
  AuthenticatedAdminPatientsNewRoute: typeof AuthenticatedAdminPatientsNewRoute
  AuthenticatedPatientDayDayRoute: typeof AuthenticatedPatientDayDayRoute
  AuthenticatedAdminPatientsIndexRoute: typeof AuthenticatedAdminPatientsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminRecipesRoute: AuthenticatedAdminRecipesRoute,
  AuthenticatedPatientLibraryRoute: AuthenticatedPatientLibraryRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedPatientIndexRoute: AuthenticatedPatientIndexRoute,
  AuthenticatedAdminPatientsIdRoute: AuthenticatedAdminPatientsIdRoute,
  AuthenticatedAdminPatientsNewRoute: AuthenticatedAdminPatientsNewRoute,
  AuthenticatedPatientDayDayRoute: AuthenticatedPatientDayDayRoute,
  AuthenticatedAdminPatientsIndexRoute: AuthenticatedAdminPatientsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
